### ISSUE TITLE
Multilingual support?

### ISSUE THREAD

**Issue by Brunty** [Brunty/cigar#11]

**Comment by mbrodala** [comment]
@Brunty what was the idea here? The description is a bit lacking. ;-)

**Comment by Brunty** [comment]
I likely threw this issue in as an idea to explore more. I'm unsure if it's needed for a tool with limited options though.

It's likely for the `.cigar.json` file. The keys that things are referenced as.

**Comment by mbrodala** [comment]
I see. But in this case having multiple files should be enough and already works. Not sure if anything more than this is necessary.

**Comment by Brunty** [comment]
Yeah, you're right. I'll close this, it can be re-opened in future if needed.
