### ISSUE TITLE
Allow to ignore incorrect SSL certificate

### ISSUE THREAD

**Issue by holtkamp** [Brunty/cigar#12]
In some cases it is required to ignore an "incorrect" SSL certificate. For example a self-signed certificate. 

This can be done by disabling peer verification:
https://curl.haxx.se/libcurl/c/CURLOPT_SSL_VERIFYPEER.html

```php
curl_setopt($channel, CURLOPT_SSL_VERIFYPEER, 0);
```

It seems that currently this kind of "overall" configuration is not supported? I could imagine a similar feature request for support of HTTP Basic Authentication...

**Comment by Brunty** [comment]
Correct, currently it's not supported, I'll look at implementing it as a flag to the tool - (unless I get beaten to it by a PR)

HTTP Basic Auth is an option too - I originally only built it to be simple at first, adding more options as needed :)
