### ISSUE TITLE
Allow authorization header

### ISSUE THREAD

**Issue by Brunty** [Brunty/cigar#17]
Allow an `--auth` (`-a`) option to pass an authorisation header string in.

**Comment by WyriHaximus** [comment]
Assuming the contents of `-a` will be put directly in the `Authorization` header?

**Comment by Brunty** [comment]
@WyriHaximus pretty much, yeah!

**Comment by WyriHaximus** [comment]
Cool I'll look into it

**Comment by WyriHaximus** [comment]
It seems @GulDmitry beat me to it :+1:
