### ISSUE TITLE
Support for PHP 7.0?

### ISSUE THREAD

**Issue by mbrodala** [Brunty/cigar#19]
We currently still have projects which use PHP 7.0 so I wonder if you would be willing to support that PHP version too.

I am aware that [PHP 7.0 is EOL at the end of this year](https://secure.php.net/supported-versions.php) but sometimes the choice is not ours. I'd still love to integrate cigar in these projects however.

**Comment by Brunty** [comment]
I don't mind supporting it if you wish to put in a PR that removes 7.1 stuff (likely just some nullable types)

**Comment by Brunty** [comment]
Thanks for the PR :)

**Comment by Brunty** [comment]
@mbrodala tagged now :)
