### ISSUE TITLE
Use a proper console tool?

### ISSUE THREAD

**Issue by Brunty** [Brunty/cigar#2]
Not sure if it's needed to use something like symfony/console etc - it feels like an unnecessary dependency, despite the niceness for options / output etc.

Cigar is a basic tool and I'm not sure it needs it.

**Comment by Brunty** [comment]
Yeah, it's got lots of awesome helper stuff (I love me some symfony/console), I'm just wondering if it's required currently for a tool with very limited scope - if more options were added to Cigar, I'd consider moving it to a symfony console app, but currently I'm not sure it'd provide any real benefit.

(For example, there's only 2 command options, `--quiet` and `--help` and the `--help` option outputs text to describe `--quiet` only)

**Comment by elstamey** [comment]
I use it for my Advent Of Code challenges because it keeps me from writing a procedural script and gives me a standard executable for all of the exercises and many commands available.

**Comment by Brunty** [comment]
Decided to reduce dependencies, right now the tool doesn't need it.
