### ISSUE TITLE
Add check for content type

### ISSUE THREAD

**Issue by WyriHaximus** [Brunty/cigar#22]
The `content` check is really useful, but I would love to see a check for the `Content-Type` header.

**Comment by Brunty** [comment]
Good idea!

**Comment by WyriHaximus** [comment]
Cool, should I make a PR or do you want to add it yourself? :)

**Comment by Brunty** [comment]
@WyriHaximus feel free to PR! I'm not going to have time to do any work on it until at least mid next week.

**Comment by WyriHaximus** [comment]
Ok cool I'll start working on it :+1:

**Comment by WyriHaximus** [comment]
PR is up at #23
