### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by WyriHaximus** [Brunty/cigar#24]
I'm toying with the idea to run cigar against production as an extra safe guard the application is still functioning as it should. Are you open to a JSON output writer?

**Comment by Brunty** [comment]
@WyriHaximus that sounds like a good idea 👍

**Comment by WyriHaximus** [comment]
Cool I'll come up with a PR soon 👍

**Comment by WyriHaximus** [comment]
PR is up at #28, it isn't complete but it shows the direction I'm thinking about

**Comment by WyriHaximus** [comment]
It's up and running, thanks for letting me PR this feature 👍🎉:

https://twitter.com/WyriHaximus/status/998609307347378176
