### ISSUE TITLE
[Idea] Also optionally check for content (e.g. regex)

### ISSUE THREAD

**Issue by asgrim** [Brunty/cigar#4]
Nice idea! Might be nice to optionally check for content (regex is probably best used here for flexibility) when making the request.

**Comment by Brunty** [comment]
@asgrim it's something I was asked about by someone else - I'm open to suggestions on it (potentially also accepting a status code range somehow)

I'd like to keep the config as simple as possible in the `.cigar` file :)

**Comment by asgrim** [comment]
`<url> <status> [<optional_regex>]` perhaps?

**Comment by Brunty** [comment]
Could do, I had a suggestion of somehow having a way to inspect headers too - but I think that's maybe going a little far.

I'll implement some regex matching of content - maybe also having a quoted string be able to be searched without having to specify it as regex so it's simple for basic matching

```
http://mysite.com 200 "Main title"
```

**Comment by Brunty** [comment]
@asgrim quick implementation of this in #6 - it doesn't use regex, just looks for a string for simplicity at the minute.

**Comment by asgrim** [comment]
Closed in #6
